FROM apache/airflow:3.1.7-python3.11

COPY requirements-airflow.txt //requirements-airflow.txt

USER root
RUN apt-get update && apt-get install -y build-essential && apt-get clean
USER airflow

RUN pip install --no-cache-dir -r /requirements-airflow.txt